#pragma once

#define	CHEAT_EXIT_BUTTON			VK_END			// button to turn off and close cheat programm
#define	CHEAT_TURN_BUTTON			VK_DELETE		// button to turn on/off cheats
#define CHEAT_RELOADCFG_BUTTON		VK_F3			// reload configuration-file

#define ESP_BUTTON					VK_NUMPAD0
#define FULLBRIGHT_BUTTON			VK_NUMPAD1
#define NOSMOKE_BUTTON				VK_NUMPAD2
#define NOFOG_BUTTON				VK_NUMPAD3
#define GLOWHACK_BUTTON				VK_NUMPAD4

#define AIMBOT_BUTTON				VK_LSHIFT
#define AIMBOT_TURN_BUTTON			VK_NUMPAD5
#define AIMBOT_TYPE_BUTTON			VK_NUMPAD6
#define AIMBOT_ANGLE_MINUS			VK_SUBTRACT
#define AIMBOT_ANGLE_PLUS			VK_ADD
#define AIMBOT_SMOOTH_MINUS			VK_NUMPAD7
#define AIMBOT_SMOOTH_PLUS			VK_NUMPAD8
#define AIMBOT_AUTOSHOOT_BUTTON		VK_NUMPAD9
#define AIMBOT_MOUSE2MODE_BUTTON	VK_PAUSE
#define AIMBOT_RANGE_MINUS			VK_DIVIDE
#define AIMBOT_RANGE_PLUS			VK_MULTIPLY
#define AIMBOT_BONENUM_PLUS			VK_RCONTROL
#define AIMBOT_BONENUM_MINUS		VK_RMENU

#define BUNNYHOP_BUTTON				VK_LMENU
#define CEILING_BUTTON				VK_CAPITAL